kind: Template
apiVersion: v1
metadata:
  name: blast-image-template
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-wildfly
labels:
  template: blast-image
objects:
  #
  # configuration
  #
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: image
    data:
      POSTGRESQL_USER: "eewfsd23rwef23re13"
      POSTGRESQL_PASSWORD: "wewsfsd234eewdsa"
      POSTGRESQL_DATABASE: blast_image
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: image
      labels:
        name: image
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_SECRET}"
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast-java.git
        contextDir: image
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: wildfly:latest
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: image:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: image
  #
  # deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: image
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - image
            from:
              kind: ImageStreamTag
              name: image:latest
        - type: ConfigChange
      replicas: 1
      selector:
        name: image
      template:
        metadata:
          labels:
            name: image
        spec:
          containers:
            - name: image
              image: image
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /blast/api/v1.0/image/x
                  port: 8080
                  scheme: HTTP
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    configMapKeyRef:
                      name: image
                      key: POSTGRESQL_USER
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: image
                      key: POSTGRESQL_PASSWORD
                - name: APP_MODULE
                  value: api:app
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: image
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: image
  #
  # route configuration
  #
  - kind: Route
    apiVersion: v1
    metadata:
      name: image
    spec:
      to:
        kind: Service
        name: image
  #
  # backend deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: image-db
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        name: image-db
      template:
        metadata:
          labels:
            name: image-db
        spec:
          containers:
            - name: image-db
              image: centos/postgresql-95-centos7:latest
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    configMapKeyRef:
                      name: image
                      key: POSTGRESQL_USER
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: image
                      key: POSTGRESQL_PASSWORD
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: image
                      key: POSTGRESQL_DATABASE
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # backend service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: image-db
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        name: image-db
#
# template parameters generation configuration
#
parameters:
  - name: GITUB_SECRET
    description: github webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: GENERIC_SECRET
    description: generic webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
